# Uncomment this line to define a global platform for your project
platform :ios, '9.1'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'assembly' do
  pod 'Analytics'
end

target 'assemblyTests' do

end
